#First, I created the name variable
name = (input('Subject, please enter your name: '))

#Next, I created the weight variable
weight = (float(input("{name}, please enter your weight in lbs: ")))

#Now we have our first print statment which is the header before the weight data
print("{name}, here are your weights on the various well-known celestial bodies in our solar system: ")

#Then, because I hate myself, I decided to get in edition to all of the planets in our solar system, I also got some of the planet's most prominent moons and neighboring large bodies
Helios = (float(weight * 28.0))
Mercury = (float(weight * .37))
Venus = (float(weight * .88))
Moon = (float(weight * .16))
Mars = (float(weight * .37))
Phobos = (float(weight * .0057))
Deimos = (float(weight * .003))
Ceres = (float(weight * .27))
Jupiter = (float(weight * 2.47))
Europa = (float(weight * .13))
Callisto = (float(weight * .12))
Io = (float(weight * .17))
Ganymede = (float(weight * .14))
Saturn = (float(weight * 1.7))
Titan = (float(weight * .13))
Uranus = (float(weight * .87))
Titania = (float(weight * .38))
Neptune = (float(weight * 1.1))
Triton = (float(weight * .78))
Pluto = (float(weight * .62))
Charon = (float(weight * .28))
Eris = (float(weight * .58))

print(f'Your weight on The Sun: {Helios:>10,.2f}'' lbs')
print(f'Your weight on Mercury: {Mercury:>10,.2f}'' lbs')
print(f'Your weight on Venus: {Venus:>10,.2f}'' lbs')
print(f'Your weight on Moon: {Moon:>12,.2f}'' lbs')
print(f'Your weight on Mars: {Mars:>12,.2f}'' lbs')
print(f'Your weight on Phobos: {Phobos:>10,.2f}'' lbs')
print(f'Your weight on Deimos: {Deimos:>10,.2f}'' lbs')
print(f'Your weight on Ceres: {Ceres:>10,.2f}'' lbs')
print(f'Your weight on Jupiter: {Jupiter:>10,.2f}'' lbs')
print(f'Your weight on Europa: {Europa:>10,.2f}'' lbs')
print(f'Your weight on Callisto: {Callisto:>10,.2f}'' lbs')
print(f'Your weight on Io: {Io:>10,.2f}'' lbs')
print(f'Your weight on Ganymede: {Ganymede:>10,.2f}'' lbs')
print(f'Your weight on Saturn: {Saturn:>10,.2f}'' lbs')
print(f'Your weight on Titan: {Titan:>10,.2f}'' lbs')
print(f'Your weight on Uranus: {Uranus:>10,.2f}'' lbs')
print(f'Your weight on Titania: {Titania:>10,.2f}'' lbs')
print(f'Your weight on Neptune: {Neptune:>10,.2f}'' lbs')
print(f'Your weight on Triton: {Triton:>10,.2f}'' lbs')
print(f'Your weight on Pluto: {Pluto:>10,.2f}'' lbs')
print(f'Your weight on Charon: {Charon:>10,.2f}'' lbs')
print(f'Your weight on Eris: {Eris:>10,.2f}'' lbs')
